In [ ]:
### /* 1.1 preprocessing data */ ###

# Original Preparation
import numpy as np
from sklearn import preprocessing
data = np.array([[3,-1.5,2,-5.4],[0,4,-0.3,2.1],[1,3.3,-1.9,-4.3]])

In [1]:
# Mean removel 以使0-中心化
data_standardized = preprocessing.scale(data)
print("\nMean = ",data_standardized.mean(axis=0))
print("Std deviation = ",data_standardized.std(axis=0))


Mean =  [ 5.55111512e-17 -1.11022302e-16 -7.40148683e-17 -7.40148683e-17]
Std deviation =  [1. 1. 1. 1.]


In [5]:
# Scaling ：可以指定扩展特征值的波动区间
data_scaler = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled = data_scaler.fit_transform(data)
print("\nMin Max scaled data = \n",data_scaled)


Min Max scaled data = 
 [[1.         0.         1.         0.        ]
 [0.         1.         0.41025641 1.        ]
 [0.33333333 0.87272727 0.         0.14666667]]


In [11]:
# Normalization 标准/正则化
data_normalized = preprocessing.normalize(data, norm='l1')  # L1正则化
print("\nL1 normalized data = \n",data_normalized)


L1 normalized data = 
 [[ 0.25210084 -0.12605042  0.16806723 -0.45378151]
 [ 0.          0.625      -0.046875    0.328125  ]
 [ 0.0952381   0.31428571 -0.18095238 -0.40952381]]


In [13]:
# Binarization 布尔二值化
data_binarized = preprocessing.Binarizer(threshold=1.4).transform(data)
print("\nBinarized data = \n",data_binarized)


Binarized data = 
 [[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [0. 1. 0. 0.]]


In [16]:
# One Hot Encoding : 统计n-维数据集中每个feature的唯一特征值个数(设k)，并将特征值由小到大排列，
# 再对该特征值执行k-维0/1编码，只有一个位=1，其他位=0

encoder_data = np.array([[0,2,1,12],[1,3,5,3],[2,3,2,12],[1,2,4,3]])
encoder = preprocessing.OneHotEncoder()
encoder.fit(encoder_data)
encoded_vector = encoder.transform([[2,3,4,3]]).toarray()
print("Original Data : \n",encoder_data)
print("\nEncoder vecter : \n",encoded_vector)

Original Data : 
 [[ 0  2  1 12]
 [ 1  3  5  3]
 [ 2  3  2 12]
 [ 1  2  4  3]]

Encoder vecter : 
 [[0. 0. 1. 0. 1. 0. 0. 1. 0. 1. 0.]]


In [20]:
### /* 1.2 Label Encoding /* ###
from sklearn import preprocessing as skpp
label_encoder = skpp.LabelEncoder() # it knows how to understand word labels,去重并排序

# create labels
input_classes = ['audi','ford','audi','toyota','ford','bmw']

# encode labels 1
label_encoder.fit(input_classes)
print("\nClass mapping:\n")
for i,item in enumerate(label_encoder.classes_):
    print(item,'-->',i)
    

# encode labels 2
print("\nencode labels : ",list(label_encoder.transform(input_classes)))

# decode numeric labels back to words
encoded_labels = [2,1,0,3,1]
print("\ndecode labels : ",list(label_encoder.inverse_transform(encoded_labels)))


Class mapping:

audi --> 0
bmw --> 1
ford --> 2
toyota --> 3

encode labels :  [0, 2, 0, 3, 2, 1]

decode labels :  ['ford', 'bmw', 'audi', 'toyota', 'bmw']
